package com.bakeflow.inventory.application;
import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;import com.bakeflow.inventory.application.InventoryDtos.*;import com.bakeflow.inventory.domain.*;import java.math.BigDecimal;import java.util.*;import org.junit.jupiter.api.*;
class InventoryCatalogServiceTests{
 ItemRepository items=mock(ItemRepository.class);BatchRepository batches=mock(BatchRepository.class);LocationRepository locations=mock(LocationRepository.class);InventoryCatalogService service=new InventoryCatalogService(items,batches,locations);
 @Test void duplicateSkuIsRejected(){when(items.existsBySku("FAR-001",null)).thenReturn(true);assertThatThrownBy(()->service.createItem(new ItemInput("Flour","FAR-001",null,ItemType.RAW_MATERIAL,UnitOfMeasure.KG,BigDecimal.ZERO))).hasMessageContaining("SKU");}
 @Test void duplicateBarcodeIsRejected(){when(items.existsByBarcode("789",null)).thenReturn(true);assertThatThrownBy(()->service.createItem(new ItemInput("Flour",null,"789",ItemType.RAW_MATERIAL,UnitOfMeasure.KG,null))).hasMessageContaining("Barcode");}
 @Test void duplicateBatchCodeForSameItemIsRejectedButDifferentItemIsAllowed(){UUID first=UUID.randomUUID(),second=UUID.randomUUID();when(items.findById(any())).thenAnswer(i->Optional.of(Item.create("Item",null,null,ItemType.OTHER,UnitOfMeasure.UNIT,null)));when(batches.existsByItemIdAndCode(first,"001",null)).thenReturn(true);assertThatThrownBy(()->service.createBatch(new BatchInput(first,"001",null,null))).hasMessageContaining("already exists");when(batches.existsByItemIdAndCode(second,"001",null)).thenReturn(false);when(batches.save(any())).thenAnswer(i->i.getArgument(0));assertThatCode(()->service.createBatch(new BatchInput(second,"001",null,null))).doesNotThrowAnyException();}
 @Test void indirectLocationCycleIsRejected(){UUID a=UUID.randomUUID(),b=UUID.randomUUID(),c=UUID.randomUUID();Location la=new Location(a,"A","A",LocationType.ROOM,b,true,null,null);Location lb=new Location(b,"B","B",LocationType.ROOM,c,true,null,null);Location lc=new Location(c,"C","C",LocationType.ROOM,null,true,null,null);when(locations.findById(a)).thenReturn(Optional.of(la));when(locations.findById(b)).thenReturn(Optional.of(lb));when(locations.findById(c)).thenReturn(Optional.of(lc));assertThatThrownBy(()->service.updateLocation(c,new LocationInput("C","C",LocationType.ROOM,a))).hasMessageContaining("cycles");}
 @Test void validHierarchyIsAccepted(){UUID parentId=UUID.randomUUID();Location parent=new Location(parentId,"Warehouse","WH",LocationType.WAREHOUSE,null,true,null,null);when(locations.findById(parentId)).thenReturn(Optional.of(parent));when(locations.existsByCode("S-1",null)).thenReturn(false);when(locations.save(any())).thenAnswer(i->i.getArgument(0));assertThat(service.createLocation(new LocationInput("Shelf","S-1",LocationType.SHELF,parentId)).parentId()).isEqualTo(parentId);}
}
