package com.bakeflow.integration.application;

import static org.assertj.core.api.Assertions.*;import com.bakeflow.integration.application.IntegrationDtos.*;import com.sun.net.httpserver.HttpServer;import java.net.*;import java.nio.charset.StandardCharsets;import java.time.*;import java.util.*;import org.junit.jupiter.api.*;import org.springframework.http.client.JdkClientHttpRequestFactory;import org.springframework.web.client.RestClient;import tools.jackson.databind.ObjectMapper;

class IntegrationServiceTests {
 private HttpServer server;private String base;private FakeCache cache;
 @BeforeEach void start()throws Exception{server=HttpServer.create(new InetSocketAddress(0),0);server.start();base="http://127.0.0.1:"+server.getAddress().getPort();cache=new FakeCache();}
 @AfterEach void stop(){server.stop(0);}
 @Test void cachesAndNormalizesProduct(){json("/api/v2/product/7891234567890.json",200,"{\"status\":1,\"product\":{\"product_name\":\"Chocolate\",\"brands\":\"Bake\",\"categories_tags\":[\"en:chocolates\"]}}");var service=service(10,3);assertThat(service.product("7891234567890","client").name()).isEqualTo("Chocolate");server.removeContext("/api/v2/product/7891234567890.json");assertThat(service.product("7891234567890","client").categories()).containsExactly("chocolates");}
 @Test void validatesAndNormalizesCnpjBeforeProviderCall(){assertThat(IntegrationService.normalizeCnpj("19.131.243/0001-97")).isEqualTo("19131243000197");assertThatThrownBy(()->IntegrationService.normalizeCnpj("11.111.111/1111-11")).isInstanceOf(IntegrationException.class);}
 @Test void enforcesRedisRateLimit(){json("/api/v2/product/7891234567890.json",200,"{\"status\":0}");var service=service(1,3);service.product("7891234567890","client");assertThatThrownBy(()->service.product("7891234567891","client")).isInstanceOf(IntegrationException.class).extracting("code").isEqualTo("RATE_LIMIT_EXCEEDED");}
 @Test void opensCircuitAfterTransientFailures(){json("/api/v2/product/7891234567890.json",500,"{}");var service=service(10,1);assertThatThrownBy(()->service.product("7891234567890","a")).isInstanceOf(IntegrationException.class);assertThatThrownBy(()->service.product("7891234567890","b")).isInstanceOf(IntegrationException.class).extracting("code").isEqualTo("CIRCUIT_BREAKER_OPEN");}
 @Test void usesExplicitStaleFallback(){json("/api/v2/product/7891234567890.json",200,"{\"status\":1,\"product\":{\"product_name\":\"Cached\"}}");var service=service(10,3);service.product("7891234567890","a");cache.delete("bakeflow:integration:openfoodfacts:barcode:7891234567890:fresh");server.removeContext("/api/v2/product/7891234567890.json");json("/api/v2/product/7891234567890.json",500,"{}");assertThat(service.product("7891234567890","b").fresh()).isFalse();}
 @Test void normalizesBrasilApiResponse(){json("/api/cnpj/v1/19131243000197",200,"{\"razao_social\":\"Padaria Demo\",\"nome_fantasia\":\"Demo\",\"municipio\":\"Recife\",\"uf\":\"PE\"}");assertThat(service(10,3).company("19.131.243/0001-97","a").legalName()).isEqualTo("Padaria Demo");}
 @Test void cacheHonorsExpiration()throws Exception{cache.set("short","value",Duration.ofMillis(5));Thread.sleep(15);assertThat(cache.get("short")).isEmpty();}
 private IntegrationService service(int limit,int threshold){var f=new JdkClientHttpRequestFactory();f.setReadTimeout(Duration.ofMillis(200));var client=RestClient.builder().baseUrl(base).requestFactory(f).build();return new IntegrationService(cache,new ObjectMapper(),client,client,Duration.ofHours(1),Duration.ofHours(1),Duration.ofDays(1),1,threshold,Duration.ofMinutes(1),limit,Duration.ofMinutes(1));}
 private void json(String path,int status,String body){server.createContext(path,e->{byte[]bytes=body.getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().add("Content-Type","application/json");e.sendResponseHeaders(status,bytes.length);e.getResponseBody().write(bytes);e.close();});}
 static class FakeCache implements CacheService{record V(String value,Instant expires){}Map<String,V>data=new HashMap<>();public Optional<String>get(String k){V v=data.get(k);if(v==null||Instant.now().isAfter(v.expires())){data.remove(k);return Optional.empty();}return Optional.of(v.value());}public void set(String k,String v,Duration t){data.put(k,new V(v,Instant.now().plus(t)));}public void delete(String k){data.remove(k);}public boolean exists(String k){return get(k).isPresent();}public boolean incrementWithinLimit(String k,int l,Duration w){int n=Integer.parseInt(get(k).orElse("0"))+1;set(k,String.valueOf(n),w);return n<=l;}public boolean available(){return true;}}
}
