package com.bakeflow.integration.application;

import static com.bakeflow.integration.application.IntegrationDtos.*;
import java.time.*;import java.util.*;import java.util.concurrent.ConcurrentHashMap;import java.util.function.Supplier;
import org.slf4j.*;import org.springframework.beans.factory.annotation.*;import org.springframework.http.HttpStatusCode;import org.springframework.stereotype.Service;import org.springframework.web.client.*;import tools.jackson.databind.*;

@Service
public class IntegrationService {
 private static final Logger log=LoggerFactory.getLogger(IntegrationService.class);
 private final CacheService cache;private final ObjectMapper json;private final RestClient off;private final RestClient brasil;
 private final Duration offTtl,brasilTtl,staleTtl;private final int retries,rateLimit;private final Duration rateWindow;
 private final SimpleCircuitBreaker offCircuit,brasilCircuit;private final Map<String,Object> locks=new ConcurrentHashMap<>();
 public IntegrationService(CacheService cache,ObjectMapper json,@Qualifier("openFoodFactsHttpClient")RestClient off,@Qualifier("brasilApiHttpClient")RestClient brasil,
  @Value("${open-food-facts.cache-ttl}")Duration offTtl,@Value("${brasil-api.cache-ttl}")Duration brasilTtl,@Value("${integrations.stale-ttl}")Duration staleTtl,
  @Value("${integrations.retry-attempts}")int retries,@Value("${integrations.circuit-failure-threshold}")int threshold,@Value("${integrations.circuit-open-duration}")Duration openDuration,
  @Value("${integrations.rate-limit}")int rateLimit,@Value("${integrations.rate-window}")Duration rateWindow){this.cache=cache;this.json=json;this.off=off;this.brasil=brasil;this.offTtl=offTtl;this.brasilTtl=brasilTtl;this.staleTtl=staleTtl;this.retries=Math.max(1,retries);this.rateLimit=rateLimit;this.rateWindow=rateWindow;offCircuit=new SimpleCircuitBreaker(threshold,openDuration);brasilCircuit=new SimpleCircuitBreaker(threshold,openDuration);}
 public ExternalProductResult product(String raw,String clientId){String barcode=raw==null?"":raw.replaceAll("\\D","");if(barcode.length()<8||barcode.length()>14)throw new IntegrationException("INVALID_BARCODE");rate("product",clientId);String key="bakeflow:integration:openfoodfacts:barcode:"+barcode;return cached(key,ExternalProductResult.class,offTtl,()->fetchProduct(barcode),offCircuit);}
 public ExternalCompanyResult company(String raw,String clientId){String cnpj=normalizeCnpj(raw);rate("company",clientId);String key="bakeflow:integration:brasilapi:company:"+cnpj;return cached(key,ExternalCompanyResult.class,brasilTtl,()->fetchCompany(cnpj),brasilCircuit);}
 public IntegrationsStatus status(){return new IntegrationsStatus(new ProviderStatus(true,offCircuit.state().name()),new ProviderStatus(true,brasilCircuit.state().name()),cache.available());}
 private void rate(String resource,String client){String safe=client==null?"unknown":client.replaceAll("[^a-zA-Z0-9:._-]","");String window=String.valueOf(Instant.now().getEpochSecond()/rateWindow.toSeconds());if(!cache.incrementWithinLimit("bakeflow:ratelimit:"+resource+":"+safe+":"+window,rateLimit,rateWindow))throw new IntegrationException("RATE_LIMIT_EXCEEDED");}
 private <T>T cached(String key,Class<T> type,Duration ttl,Supplier<T> supplier,SimpleCircuitBreaker circuit){Optional<T> hit=read(key,type);if(hit.isPresent()){log.debug("Integration cache status=HIT key={}",key);return hit.get();}log.debug("Integration cache status=MISS key={}",key);Object lock=locks.computeIfAbsent(key,k->new Object());synchronized(lock){try{hit=read(key,type);if(hit.isPresent())return hit.get();if(!circuit.allow())return staleOrThrow(key,type,"CIRCUIT_BREAKER_OPEN");long start=System.nanoTime();try{T value=retry(supplier);circuit.success();write(key,value,ttl.plus(staleTtl));cache.set(key+":fresh","1",ttl);log.info("External integration status=SUCCESS durationMs={}",(System.nanoTime()-start)/1_000_000);return value;}catch(RuntimeException e){circuit.failure();String code=e instanceof ResourceAccessException?"EXTERNAL_SERVICE_TIMEOUT":"EXTERNAL_SERVICE_UNAVAILABLE";log.warn("External integration status=FAILURE category={}",e.getClass().getSimpleName());return staleOrThrow(key,type,code);}}finally{locks.remove(key,lock);}}}
 private <T>Optional<T> read(String key,Class<T> type){return cache.get(key).flatMap(v->{try{T value=json.readValue(v,type);if(cache.exists(key+":fresh"))return Optional.of(value);return Optional.empty();}catch(Exception e){cache.delete(key);return Optional.empty();}});}
 private <T>T staleOrThrow(String key,Class<T> type,String code){return cache.get(key).map(v->{try{return markStale(json.readValue(v,type));}catch(Exception e){return null;}}).filter(Objects::nonNull).orElseThrow(()->new IntegrationException(code));}
 @SuppressWarnings("unchecked") private <T>T markStale(T value){if(value instanceof ExternalProductResult p)return(T)new ExternalProductResult(p.status(),p.barcode(),p.name(),p.brand(),p.quantity(),p.imageUrl(),p.categories(),p.source(),false,p.errorCode());if(value instanceof ExternalCompanyResult c)return(T)new ExternalCompanyResult(c.status(),c.taxId(),c.legalName(),c.tradeName(),c.companyStatus(),c.street(),c.number(),c.district(),c.city(),c.state(),c.postalCode(),c.source(),false,c.errorCode());return value;}
 private void write(String key,Object value,Duration ttl){try{cache.set(key,json.writeValueAsString(value),ttl);}catch(Exception ignored){}}
 private <T>T retry(Supplier<T> action){RuntimeException last=null;for(int i=0;i<retries;i++){try{return action.get();}catch(HttpClientErrorException e){throw e;}catch(RuntimeException e){last=e;if(i+1<retries)try{Thread.sleep(100L*(i+1));}catch(InterruptedException x){Thread.currentThread().interrupt();throw e;}}}throw last;}
 private ExternalProductResult fetchProduct(String barcode){try{JsonNode root=off.get().uri("/api/v2/product/{barcode}.json?fields=code,product_name,brands,image_front_url,quantity,categories_tags",barcode).retrieve().body(JsonNode.class);if(root==null||root.path("status").asInt()==0)return new ExternalProductResult(ResultStatus.NOT_FOUND,barcode,null,null,null,null,List.of(),DataSource.OPEN_FOOD_FACTS,true,"EXTERNAL_RESOURCE_NOT_FOUND");JsonNode p=root.path("product");if(!p.isObject())throw new IllegalStateException("Invalid provider payload");List<String>categories=new ArrayList<>();if(p.path("categories_tags").isArray())p.path("categories_tags").forEach(n->{if(n.isTextual()&&categories.size()<20)categories.add(n.asText().replaceFirst("^[a-z]{2}:","").replace('-',' '));});return new ExternalProductResult(ResultStatus.FOUND,barcode,text(p,"product_name",160),text(p,"brands",160),text(p,"quantity",80),text(p,"image_front_url",500),categories,DataSource.OPEN_FOOD_FACTS,true,null);}catch(HttpClientErrorException.NotFound e){return new ExternalProductResult(ResultStatus.NOT_FOUND,barcode,null,null,null,null,List.of(),DataSource.OPEN_FOOD_FACTS,true,"EXTERNAL_RESOURCE_NOT_FOUND");}}
 private ExternalCompanyResult fetchCompany(String cnpj){try{JsonNode n=brasil.get().uri("/api/cnpj/v1/{cnpj}",cnpj).retrieve().body(JsonNode.class);if(n==null||!n.isObject())throw new IllegalStateException("Invalid provider payload");return new ExternalCompanyResult(ResultStatus.FOUND,cnpj,text(n,"razao_social",200),text(n,"nome_fantasia",200),text(n,"descricao_situacao_cadastral",80),text(n,"logradouro",200),text(n,"numero",30),text(n,"bairro",120),text(n,"municipio",120),text(n,"uf",2),text(n,"cep",12),DataSource.BRASIL_API,true,null);}catch(HttpClientErrorException.NotFound e){return new ExternalCompanyResult(ResultStatus.NOT_FOUND,cnpj,null,null,null,null,null,null,null,null,null,DataSource.BRASIL_API,true,"EXTERNAL_RESOURCE_NOT_FOUND");}}
 private String text(JsonNode n,String field,int max){JsonNode v=n.path(field);if(!v.isTextual()&&!v.isNumber())return null;String s=v.asText().trim();return s.isEmpty()?null:s.substring(0,Math.min(s.length(),max));}
 static String normalizeCnpj(String raw){String n=raw==null?"":raw.replaceAll("\\D","");if(n.length()!=14||n.chars().distinct().count()==1||!validCnpj(n))throw new IntegrationException("INVALID_CNPJ");return n;}
 private static boolean validCnpj(String n){int[]w1={5,4,3,2,9,8,7,6,5,4,3,2},w2={6,5,4,3,2,9,8,7,6,5,4,3,2};return digit(n.substring(0,12),w1)==n.charAt(12)-48&&digit(n.substring(0,13),w2)==n.charAt(13)-48;}
 private static int digit(String n,int[]w){int sum=0;for(int i=0;i<w.length;i++)sum+=(n.charAt(i)-48)*w[i];int r=sum%11;return r<2?0:11-r;}
}
